CREATE TABLE `training_data` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `time` datetime NOT NULL,
  `latitude` float DEFAULT NULL,
  `longitude` float DEFAULT NULL,
  `dewPoint` float DEFAULT NULL,
  `humidity` float DEFAULT NULL,
  `pressure` float DEFAULT NULL,
  `windSpeed` float DEFAULT NULL,
  `windGust` float DEFAULT NULL,
  `windBearing` float DEFAULT NULL,
  `cloudCover` float DEFAULT NULL,
  `uvIndex` float DEFAULT NULL,
  `visibility` float DEFAULT NULL,
  `ozone` float DEFAULT NULL,
  `precipProbability` float DEFAULT NULL,
  `precipType` varchar(64) DEFAULT NULL,
  `precipIntensity` float DEFAULT NULL,
  `precipIntensityError` float DEFAULT NULL,
  `temperature` float DEFAULT NULL,
  `feelsTemperature` float DEFAULT NULL,
  `clothes` int(10) unsigned NOT NULL,
  `transport` int(10) unsigned NOT NULL,
  `umbrella` tinyint(1) NOT NULL,
  `rainjacket` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
